apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-gateway
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
data:
  SPRING_SECURITY_USER_NAME: {{ .Values.apiGateway.username | b64enc }}
  SPRING_SECURITY_USER_PASSWORD: {{ .Values.apiGateway.password | b64enc }}
  SPRING_SENDGRID_API-KEY: {{ .Values.sendGrid.apiKey | b64enc }}
