apiVersion: v1
kind: Service
metadata:
  labels:
    app: apm-server-jaeger
  name: jenkins-x-apm-server-jaeger
spec:
  ports:
  - name: http
    port: 14268
    protocol: TCP
    targetPort: 14268
  selector:
    app: apm-server
    release: jenkins-x
  sessionAffinity: None
  type: ClusterIP
