apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: basic-auth
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
data:
  auth: {{ .Values.htpasswd | b64enc }}
