apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cms-secrets
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
data:
  jwtSigningKey: {{ .Values.cms.jwtSigningKey | b64enc }}
