---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: jx
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    setup.kibana.host: http://jenkins-x-kibana.jx:5601
    setup.dashboards.enabled: true
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/jx-strapi*.log
        - /var/log/containers/jx-react*.log
        - /var/log/containers/jenkins-x-harbor*.log
        - /var/log/containers/jenkins-x-keycloak*.log
        - /var/log/containers/jenkins-x-mongodb*.log
        - /var/log/containers/jenkins-x-nexus*.log
        - /var/log/containers/jenkins-x-octant*.log
        - /var/log/containers/jenkins-x-pact*.log
        - /var/log/containers/jenkins-x-postgres*.log
        - /var/log/containers/elastic*.log
        - /var/log/containers/kafka*.log
      exclude_lines: ['DEBUG', 'debug', 'TRACE', 'trace', 'kube-probe', '\/api\/ping']
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
    - type: container
      paths:
        - /var/log/containers/jx-api-gateway*.log
        - /var/log/containers/jx-start*.log
        - /var/log/containers/jenkins-x-kibana*.log
      exclude_lines: ['DEBUG', 'debug', 'TRACE', 'trace']
      json:
        keys_under_root: true
        message_key: message
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
    - type: container
      paths:
        - /var/log/containers/jx-search*.log
      exclude_lines: ['DEBUG', 'debug', 'TRACE', 'trace']
      multiline:
        type: pattern
        pattern: '^[[:space:]]'
        negate: false
        match: after
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    # To enable hints based autodiscover, remove `filebeat.inputs` configuration and uncomment this:
    #filebeat.autodiscover:
    #  providers:
    #    - type: kubernetes
    #      node: ${NODE_NAME}
    #      hints.enabled: true
    #      hints.default_config:
    #        type: container
    #        paths:
    #          - /var/log/containers/*${data.kubernetes.container.id}.log

    processors:
      - add_cloud_metadata:
      - add_host_metadata:

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: jx
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.11.0
          args: [
              "-c", "/etc/filebeat.yml",
              "-e",
          ]
          env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch-master.jx
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: data
              mountPath: /usr/share/filebeat/data
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 0640
            name: filebeat-config
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log
        # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
        - name: data
          hostPath:
            # When filebeat runs as non-root user, this directory needs to be writable by group (g+w).
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: jx
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: jx
  labels:
    k8s-app: filebeat
---