apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-gradle-init
data:
  init.gradle: {{ .Values.gradle.initScript | b64enc }}
  gradle.properties: {{ .Values.gradle.properties | b64enc }}