apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-magic
spec:
  selector:
    matchLabels:
      app: kafka-magic
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-magic
      annotations: {}
    spec:
      containers:
      - name: kafka-magic
        image: digitsy/kafka-magic
        imagePullPolicy: Always
        env:
        - name: KMAGIC_ALLOW_TOPIC_DELETE
          value: "true"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-magic
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/auth-type: basic\nnginx.ingress.kubernetes.io/auth-secret: basic-auth\nnginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: kafka-magic

