apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pact-broker
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
data:
  PACT_BROKER_DATABASE_PASSWORD: {{ .Values.mongo.rootPassword | b64enc }}
  PACT_BROKER_BASIC_AUTH_USERNAME: {{ .Values.pactBroker.username | b64enc }}
  PACT_BROKER_BASIC_AUTH_PASSWORD: {{ .Values.pactBroker.password | b64enc }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pact-broker
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
data:
  PACT_BROKER_DATABASE_ADAPTER: postgres
  PACT_BROKER_DATABASE_USERNAME: postgres
  PACT_BROKER_DATABASE_HOST: jenkins-x-postgresql
  PACT_BROKER_DATABASE_NAME: pact
  PACT_BROKER_DATABASE_PORT: "5432"

