adminUser:
  htpasswd: local:simonjamesrowe/adminUser:htpasswd
  password: local:simonjamesrowe/adminUser:password
  username: admin
apiGateway:
  password: local:simonjamesrowe/apiGateway:password
  username: webhook
aws:
  accessKeyId: local:simonjamesrowe/aws:accessKeyId
  accessSecret: local:simonjamesrowe/aws:accessSecret
  hostedZoneId: local:simonjamesrowe/aws:hostedZoneId
docker:
  email: simon@simonjamesrowe.com
  password: local:simonjamesrowe/docker:password
  url: harbor.simonjamesrowe.com
  username: admin
enableDocker: true
mongo:
  rootPassword: local:simonjamesrowe/mongo:rootPassword
pactBroker:
  password: local:simonjamesrowe/pactBroker:password
  username: pact
pipelineUser:
  email: simon@simonjamesrowe.com
  token: local:simonjamesrowe/pipelineUser:token
  username: simonrowe-bot
prow:
  hmacToken: local:simonjamesrowe/prow:hmacToken
sendGrid:
  apiKey: local:simonjamesrowe/sendGrid:apiKey
sonarqube:
  apiKey: local:simonjamesrowe/sonarqube:apiKey
strapi:
  jwtSigningKey: local:simonjamesrowe/strapi:jwtSigningKey
