dependencies:
- name: jxboot-resources
  repository: http://chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
- alias: lighthouse-jx
  condition: lighthouse.enabled
  name: lighthouse-jx
  repository: http://chartmuseum.jenkins-x.io
- alias: bucketrepo
  condition: bucketrepo.enabled
  name: bucketrepo
  repository: http://chartmuseum.jenkins-x.io
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
- alias: harbor
  name: harbor
  repository: https://helm.goharbor.io
  version: 1.3.2
- alias: mongodb
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 7.14.0
- alias: kubernetes-replicator
  name: kubernetes-replicator
  repository: https://helm.mittwald.de
  version: 2.3.0
- name: octant
  repository: https://chartmuseum-jx.simonjamesrowe.com/
  version: 0.0.12
- name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.10.0
- name: kibana
  repository: https://helm.elastic.co
  version: 7.10.0
- name: apm-server
  repository: https://helm.elastic.co
  version: 7.10.0
- name: cp-helm-charts
  repository: https://confluentinc.github.io/cp-helm-charts/
  version: 0.6.0
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 9.8.12
- name: pact-broker
  repository: https://chartmuseum-jx.simonjamesrowe.com/
  version: 0.0.6
- name: keycloak
  repository: https://codecentric.github.io/helm-charts
  version: 9.9.2
- name: sonarqube
  repository: https://chartmuseum-jx.simonjamesrowe.com/
  version: 0.0.1


