dependencies:
- name: jxboot-resources
  repository: http://chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
- alias: bucketrepo
  condition: bucketrepo.enabled
  name: bucketrepo
  repository: http://chartmuseum.jenkins-x.io
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
- alias: harbor
  name: harbor
  repository: https://helm.goharbor.io
  version: 1.3.2
- alias: mongodb
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 7.14.0
- alias: kubernetes-replicator
  name: kubernetes-replicator
  repository: https://helm.mittwald.de
  version: 2.3.0
- name: jx-app-ui
  repository: http://chartmuseum.jenkins-x.io
  version: 0.1.211
